name: Sync example notebooks from main PGM repo to PGM-workshop

on:
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PGM workshop repository
        uses: actions/checkout@v4
